import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Head from 'next/head'
import LeftBar from '@/components/LeftBar'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Footer />
      <LeftBar />
    </>
  )
}
